collections:
  - name: community.general
  - name: redpanda.cluster
    type: galaxy

roles:
  - src: mrlesmithjr.mdadm
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.grafana
  - src: geerlingguy.node_exporter
